name: Build and Test
run-name: ${{ github.actor }} is building and testing project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Store Build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            build/libPokerEquity.so
            build/libPokerEval.a
            build/PokerEquityTest
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Load Build
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
      - name: Test
        run: |
          ls -larth
          build/PokerEquityTest
