name: Build and Test
run-name: ${{ github.actor }} is building and testing project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ls -larth
          ls -larth Poker.PokerEval/
      - name: Store Build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            build/libPokerEquity.so
            build/libPokerEval.a
            build/PokerEquityTest
            build/Poker.PokerEval/joktest1
            build/Poker.PokerEval/enumtest1
            build/Poker.PokerEval/enumtest2
            build/Poker.PokerEval/enumtest3
            build/Poker.PokerEval/enumtest5
            build/Poker.PokerEval/enumtest7
            build/Poker.PokerEval/poker_wrapper
            build/Poker.PokerEval/razz
            build/Poker.PokerEval/pokenum
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Load Build
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build
      - name: Test
        run: |
          ls -larth
          ls -larth build/
          chmod +x ./build/PokerEquityTest
          chmod +x ./build/Poker.PokerEval/joktest1
          chmod +x ./build/Poker.PokerEval/enumtest1
          chmod +x ./build/Poker.PokerEval/enumtest2
          chmod +x ./build/Poker.PokerEval/enumtest3
          chmod +x ./build/Poker.PokerEval/enumtest5
          chmod +x ./build/Poker.PokerEval/enumtest7
          chmod +x ./build/Poker.PokerEval/poker_wrapper
          chmod +x ./build/Poker.PokerEval/razz
          chmod +x ./build/Poker.PokerEval/pokenum
          ./build/PokerEquityTest
          [ $(./build/Poker.PokerEval/enumtest1 6 3 | md5sum | awk '{print $1}') = 425daf38998180d6f261ac6801d589dd ]
          [ $(./build/Poker.PokerEval/enumtest2 | md5sum | awk '{print $1}') = 1e144704f542b3046c174bcfc3c1f2a2 ]
          [ $(./build/Poker.PokerEval/enumtest3 | md5sum | awk '{print $1}') = 8eca9e9a0aa0e4ad71acafbc8a93da4a ]
          [ $(./build/Poker.PokerEval/enumtest5 | md5sum | awk '{print $1}') = 74c0f1347023859feab2275dc8c33ef1 ]
          [ $(./build/Poker.PokerEval/enumtest7 | md5sum | awk '{print $1}') = 02d548445d51f7ddf2b99ff878b49277 ]
          
          ./build/Poker.PokerEval/razz
          ./build/Poker.PokerEval/poker_wrapper
          ./build/Poker.PokerEval/pokenum -h Ac 7c - 5s 4s - Ks Kd -- 7h 2c 3h
          ./build/Poker.PokerEval/pokenum -h Ac 7c - 5s 4s - Ks Kd -- 7h 2c 3h / Ah
          
          ./build/Poker.PokerEval/pokenum -h8 Ac 7c  5s 4s  Ks Kd -- 7h 2c 3h
          
          ./build/Poker.PokerEval/pokenum -o As Kh Qs Jh - 8h 8d 7h 6d -- 8s Ts Jc
          
          ./build/Poker.PokerEval/pokenum -o8 As Kh Qs Jh - 8h 8d 7h 6d -- 8s Ts Jc
          
          ./build/Poker.PokerEval/pokenum -7s As Ah Ts Th 8h 8d - Kc Qc Jc Td 3c 2d - Ac 2h 3h 3d 7s 7h
          ./build/Poker.PokerEval/pokenum -7s As Ah Ts Th 8h 8d - Kc Qc Jc Td 3c 2d - Ac 2h 3h 3d 7s 7h / 5c 6c 7c
          
          ./build/Poker.PokerEval/pokenum -7s8 As Ah Ts Th 8h 8d - Kc Qc Jc Td 3c 2d - Ac 2h 3h 3d 7s 7h
          ./build/Poker.PokerEval/pokenum -7s8 As Ah Ts Th 8h 8d - Kc Qc Jc Td 3c 2d - Ac 2h 3h 3d 7s 7h / 5c 6c 7c
          
          ./build/Poker.PokerEval/pokenum -7snsq As Ah Ts Th 8h 8d - Kc Qc Jc Td 3c 2d - Ac 2h 3h 3d 7s 7h
          ./build/Poker.PokerEval/pokenum -7snsq As Ah Ts Th 8h 8d - Kc Qc Jc Td 3c 2d - Ac 2h 3h 3d 7s 7h / 5c 6c 7c
          
          ./build/Poker.PokerEval/pokenum -r As 2s 3s 4s Kh - Th 9h 8h 7h 6h / Qd Jd Td 9d
           
          ./build/Poker.PokerEval/pokenum -l27 As 2s 3s 4s 5d - Ac 3c 4c 5c 6d
          ./build/Poker.PokerEval/pokenum -l27 5h 4h 3h 2h / 5s - 9s 8h 6d 4c / Kd
          
          ./build/Poker.PokerEval/pokenum -mc 10000 -h Ac 7c - 5s 4s - Ks Kd
          ./build/Poker.PokerEval/pokenum -mc 10000 -h Ac 7c - 5s 4s - Ks Kd -- 7h 2c 3h
          ./build/Poker.PokerEval/pokenum -mc 10000 -h8 Ac 7c - 5s 4s - Ks Kd
          ./build/Poker.PokerEval/pokenum -mc 10000 -o As Kh Qs Jh - 8h 8d 7h 6d
          ./build/Poker.PokerEval/pokenum -mc 10000 -o8 As Kh Qs Jh - 8h 8d 7h 6d
          ./build/Poker.PokerEval/pokenum -mc 10000 -7s As Ah Ts -  7c 6c 5c
          ./build/Poker.PokerEval/pokenum -mc 10000 -7s8 As Ah Ts - 7c 6c 5c
          ./build/Poker.PokerEval/pokenum -mc 10000 -7snsq As Ah Ts -  7c 6c 5c
          ./build/Poker.PokerEval/pokenum -mc 10000 -r As 2s 3s 4s Kh - Th 9h 8h 7h 6h / Qd Jd Td 9d
          ./build/Poker.PokerEval/pokenum -mc 10000 -l27 5h 4h 3h 2h / 5s - 9s 8h 6d 4c / Kd
          ./build/Poker.PokerEval/pokenum -mc 10000 -l27 5h 4h 3h / 5s Qd - 9s 8h 6d / Kd Ks